source 'https://github.com/CocoaPods/Specs.git'
source 'git@gitlab.com:set.app/ios/setpods.git'
use_frameworks!
platform :ios, '9.0'

target 'XJBase_Example' do
  pod 'XJBase', :path => '../'

  target 'XJBase_Tests' do
    inherit! :search_paths

    
  end
end
