source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
platform :ios, '9.0'

target 'XJBase_Example' do
  pod 'XJBase', :path => '../'
  pod 'AFNetworking'
  pod 'Masonry'
  
  target 'XJBase_Tests' do
    inherit! :search_paths

    
  end
end
